name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 원격 저장소에서 코드 가져오기
      - uses: actions/checkout@v4

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 환경변수 가져오기
      - name: Load environment variables
        env:
          DB_PROD_URL: ${{ secrets.DB_PROD_URL }}
          DB_PROD_USER: ${{ secrets.DB_PROD_USER }}
          DB_PROD_PASSWORD: ${{ secrets.DB_PROD_PASSWORD }}
          REDIS_PROD_HOST: ${{ secrets.REDIS_PROD_HOST }}
          REDIS_PROD_PORT: ${{ secrets.REDIS_PROD_PORT }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: echo "Environment variables loaded."

      # gradle 실행 권한 부여
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # Gradle 빌드 실행 (테스트 생략)
      - name: Build with Gradle Wrapper (Skip Tests)
        run: ./gradlew build -x test
